### ISSUE TITLE
Post_Dropdown_Custom_Control

### ISSUE THREAD

**Issue by edgarscr** [bueltge/WordPress-Theme-Customizer-Custom-Controls#2]
hello howdy? im testing Post_Dropdown_Custom_Control but i dont know how to display can you explain me please. 

i try with **echo get_theme_mod('post_dropdown_setting');** and nthing display

**Comment by bueltge** [comment]
You must need to use the [Customizer API](https://developer.wordpress.org/themes/customize-api/), like [`$wp_customize->add_control(`](https://codex.wordpress.org/Class_Reference/WP_Customize_Manager/add_control)

See also the two examples on the other tow classes to understand how it works.
